# Generated by Django 5.1.1 on 2024-09-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('category', models.CharField(choices=[('testnet', 'Тестнет'), ('mainnet', 'Мейннет')], default='testnet', max_length=50, verbose_name='Категория')),
                ('project_info', models.TextField(verbose_name='Информация о проекте')),
                ('investment_info', models.TextField(verbose_name='Информация об инвестициях')),
                ('potential_info', models.TextField(verbose_name='Информация о потенциале')),
                ('accounts_order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('accounts_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('points_order_name', models.CharField(blank=True, max_length=255, null=True)),
                ('points_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('activity1_name', models.CharField(max_length=255, verbose_name='Название Активности 1')),
                ('activity1_task', models.TextField(verbose_name='Описание Активности 1')),
                ('activity1_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена Активности 1')),
                ('activity2_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Активности 2')),
                ('activity2_task', models.TextField(blank=True, null=True, verbose_name='Описание Активности 2')),
                ('activity2_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Активности 2')),
                ('activity3_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Активности 3')),
                ('activity3_task', models.TextField(blank=True, null=True, verbose_name='Описание Активности 3')),
                ('activity3_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Активности 3')),
                ('activity4_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Активности 4')),
                ('activity4_task', models.TextField(blank=True, null=True, verbose_name='Описание Активности 4')),
                ('activity4_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Активности 4')),
                ('activity5_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Активности 5')),
                ('activity5_task', models.TextField(blank=True, null=True, verbose_name='Описание Активности 5')),
                ('activity5_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Активности 5')),
                ('activity6_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Активности 6')),
                ('activity6_task', models.TextField(blank=True, null=True, verbose_name='Описание Активности 6')),
                ('activity6_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Активности 6')),
                ('activity7_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Активности 7')),
                ('activity7_task', models.TextField(blank=True, null=True, verbose_name='Описание Активности 7')),
                ('activity7_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Активности 7')),
                ('activity8_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Активности 8')),
                ('activity8_task', models.TextField(blank=True, null=True, verbose_name='Описание Активности 8')),
                ('activity8_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Активности 8')),
                ('activity9_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Активности 9')),
                ('activity9_task', models.TextField(blank=True, null=True, verbose_name='Описание Активности 9')),
                ('activity9_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Активности 9')),
                ('activity10_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название Активности 10')),
                ('activity10_task', models.TextField(blank=True, null=True, verbose_name='Описание Активности 10')),
                ('activity10_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена Активности 10')),
            ],
        ),
    ]
